tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
# tap "snyk/tap"
tap "supabase/tap"
tap "yqrashawn/goku"

brew "autojump"
brew "brew-cask-completion"
# brew "python@3.9"
# brew "colima"
# brew "direnv"
brew "docker"
brew "docker-compose"
brew "git"
brew "jq"
brew "mas"
brew "terraform"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "supabase/tap/supabase"
brew "yqrashawn/goku/goku"

# cask "brave-browser"
# cask "dozer"
# cask "font-fira-code"
# # cask "mos"
# cask "rectangle"
# cask "signal"
# cask "slack"
# cask "spotify"

# mas "ColorSlurp", id: 1287239339
# mas "Hand Mirror", id: 1502839586
# mas "Tonebridge Guitar Effects", id: 1263858588
